services:
  postgres:
    container_name: postgres-sql-plantilla-Login
    image: postgres
    environment:
      POSTGRES_USER: andresito
      POSTGRES_PASSWORD: pelusa
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: plantilla_login
    volumes:
      - postgres:/data/postgres

    ports:
      - 5432:5432

    networks:
      - spring-demo

    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-login
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local