services:
  - type: web
    name: sistema-gimnasio-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/v1/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: gimnasio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gimnasio-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gimnasio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gimnasio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gimnasio-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

databases:
  - name: gimnasio-db
    plan: free # El plan gratuito de Render DB dura 30 días
