server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/sistema_gym
    username: postgres
    password: ${DB_PASSWORD:pelusa}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Revertido a update tras la recreación inicial
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect







application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:Qx9L2mR7T4ZCwEJp8DkS5A6HfYVbN0UeXW3M7N4JcRZpUeA2S9H5LkX}
      expiration: 8640000

storage:
  comprobantes-dir: storage/comprobantes

